site_name: My Notes
site_url: https://nagaarjun-p.github.io/notes/
theme:
  name: material
nav:
  - Home: index.md
  - Notes:
      - First Note: notes/first-note.md
      - Subject 1: docs/notes/
        - day 1 : docs/notes/subject1/day1.md
